export interface Country {
  name:  string
  code:  string   // ISO 3166-1 alpha-2
  dial:  string   // e.g. "+44"
  flag:  string   // emoji flag
}

// Pinned at top of the dropdown
export const PINNED_COUNTRIES: Country[] = [
  { name: 'United Kingdom', code: 'GB', dial: '+44',  flag: '🇬🇧' },
  { name: 'United States',  code: 'US', dial: '+1',   flag: '🇺🇸' },
  { name: 'Canada',         code: 'CA', dial: '+1',   flag: '🇨🇦' },
  { name: 'Australia',      code: 'AU', dial: '+61',  flag: '🇦🇺' },
  { name: 'South Africa',   code: 'ZA', dial: '+27',  flag: '🇿🇦' },
  { name: 'Pakistan',       code: 'PK', dial: '+92',  flag: '🇵🇰' },
  { name: 'India',          code: 'IN', dial: '+91',  flag: '🇮🇳' },
  { name: 'Bangladesh',     code: 'BD', dial: '+880', flag: '🇧🇩' },
  { name: 'Nigeria',        code: 'NG', dial: '+234', flag: '🇳🇬' },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971', flag: '🇦🇪' },
  { name: 'Saudi Arabia',   code: 'SA', dial: '+966', flag: '🇸🇦' },
  { name: 'Malaysia',       code: 'MY', dial: '+60',  flag: '🇲🇾' },
  { name: 'Turkey',         code: 'TR', dial: '+90',  flag: '🇹🇷' },
  { name: 'Egypt',          code: 'EG', dial: '+20',  flag: '🇪🇬' },
]

// Full list (alphabetical, excluding already-pinned)
export const ALL_COUNTRIES: Country[] = [
  { name: 'Afghanistan',           code: 'AF', dial: '+93',   flag: '🇦🇫' },
  { name: 'Albania',               code: 'AL', dial: '+355',  flag: '🇦🇱' },
  { name: 'Algeria',               code: 'DZ', dial: '+213',  flag: '🇩🇿' },
  { name: 'Argentina',             code: 'AR', dial: '+54',   flag: '🇦🇷' },
  { name: 'Armenia',               code: 'AM', dial: '+374',  flag: '🇦🇲' },
  { name: 'Austria',               code: 'AT', dial: '+43',   flag: '🇦🇹' },
  { name: 'Azerbaijan',            code: 'AZ', dial: '+994',  flag: '🇦🇿' },
  { name: 'Bahrain',               code: 'BH', dial: '+973',  flag: '🇧🇭' },
  { name: 'Belgium',               code: 'BE', dial: '+32',   flag: '🇧🇪' },
  { name: 'Bosnia & Herzegovina',  code: 'BA', dial: '+387',  flag: '🇧🇦' },
  { name: 'Brazil',                code: 'BR', dial: '+55',   flag: '🇧🇷' },
  { name: 'Brunei',                code: 'BN', dial: '+673',  flag: '🇧🇳' },
  { name: 'Bulgaria',              code: 'BG', dial: '+359',  flag: '🇧🇬' },
  { name: 'Cameroon',              code: 'CM', dial: '+237',  flag: '🇨🇲' },
  { name: 'Chad',                  code: 'TD', dial: '+235',  flag: '🇹🇩' },
  { name: 'China',                 code: 'CN', dial: '+86',   flag: '🇨🇳' },
  { name: 'Comoros',               code: 'KM', dial: '+269',  flag: '🇰🇲' },
  { name: 'Croatia',               code: 'HR', dial: '+385',  flag: '🇭🇷' },
  { name: 'Cyprus',                code: 'CY', dial: '+357',  flag: '🇨🇾' },
  { name: 'Czech Republic',        code: 'CZ', dial: '+420',  flag: '🇨🇿' },
  { name: 'Denmark',               code: 'DK', dial: '+45',   flag: '🇩🇰' },
  { name: 'Djibouti',              code: 'DJ', dial: '+253',  flag: '🇩🇯' },
  { name: 'Ethiopia',              code: 'ET', dial: '+251',  flag: '🇪🇹' },
  { name: 'Finland',               code: 'FI', dial: '+358',  flag: '🇫🇮' },
  { name: 'France',                code: 'FR', dial: '+33',   flag: '🇫🇷' },
  { name: 'Gambia',                code: 'GM', dial: '+220',  flag: '🇬🇲' },
  { name: 'Germany',               code: 'DE', dial: '+49',   flag: '🇩🇪' },
  { name: 'Ghana',                 code: 'GH', dial: '+233',  flag: '🇬🇭' },
  { name: 'Greece',                code: 'GR', dial: '+30',   flag: '🇬🇷' },
  { name: 'Guinea',                code: 'GN', dial: '+224',  flag: '🇬🇳' },
  { name: 'Hungary',               code: 'HU', dial: '+36',   flag: '🇭🇺' },
  { name: 'Indonesia',             code: 'ID', dial: '+62',   flag: '🇮🇩' },
  { name: 'Iran',                  code: 'IR', dial: '+98',   flag: '🇮🇷' },
  { name: 'Iraq',                  code: 'IQ', dial: '+964',  flag: '🇮🇶' },
  { name: 'Ireland',               code: 'IE', dial: '+353',  flag: '🇮🇪' },
  { name: 'Israel',                code: 'IL', dial: '+972',  flag: '🇮🇱' },
  { name: 'Italy',                 code: 'IT', dial: '+39',   flag: '🇮🇹' },
  { name: 'Ivory Coast',           code: 'CI', dial: '+225',  flag: '🇨🇮' },
  { name: 'Japan',                 code: 'JP', dial: '+81',   flag: '🇯🇵' },
  { name: 'Jordan',                code: 'JO', dial: '+962',  flag: '🇯🇴' },
  { name: 'Kazakhstan',            code: 'KZ', dial: '+7',    flag: '🇰🇿' },
  { name: 'Kenya',                 code: 'KE', dial: '+254',  flag: '🇰🇪' },
  { name: 'Kosovo',                code: 'XK', dial: '+383',  flag: '🇽🇰' },
  { name: 'Kuwait',                code: 'KW', dial: '+965',  flag: '🇰🇼' },
  { name: 'Kyrgyzstan',            code: 'KG', dial: '+996',  flag: '🇰🇬' },
  { name: 'Lebanon',               code: 'LB', dial: '+961',  flag: '🇱🇧' },
  { name: 'Libya',                 code: 'LY', dial: '+218',  flag: '🇱🇾' },
  { name: 'Luxembourg',            code: 'LU', dial: '+352',  flag: '🇱🇺' },
  { name: 'Mali',                  code: 'ML', dial: '+223',  flag: '🇲🇱' },
  { name: 'Mauritania',            code: 'MR', dial: '+222',  flag: '🇲🇷' },
  { name: 'Mauritius',             code: 'MU', dial: '+230',  flag: '🇲🇺' },
  { name: 'Mexico',                code: 'MX', dial: '+52',   flag: '🇲🇽' },
  { name: 'Morocco',               code: 'MA', dial: '+212',  flag: '🇲🇦' },
  { name: 'Mozambique',            code: 'MZ', dial: '+258',  flag: '🇲🇿' },
  { name: 'Netherlands',           code: 'NL', dial: '+31',   flag: '🇳🇱' },
  { name: 'New Zealand',           code: 'NZ', dial: '+64',   flag: '🇳🇿' },
  { name: 'Niger',                 code: 'NE', dial: '+227',  flag: '🇳🇪' },
  { name: 'Norway',                code: 'NO', dial: '+47',   flag: '🇳🇴' },
  { name: 'Oman',                  code: 'OM', dial: '+968',  flag: '🇴🇲' },
  { name: 'Palestine',             code: 'PS', dial: '+970',  flag: '🇵🇸' },
  { name: 'Philippines',           code: 'PH', dial: '+63',   flag: '🇵🇭' },
  { name: 'Poland',                code: 'PL', dial: '+48',   flag: '🇵🇱' },
  { name: 'Portugal',              code: 'PT', dial: '+351',  flag: '🇵🇹' },
  { name: 'Qatar',                 code: 'QA', dial: '+974',  flag: '🇶🇦' },
  { name: 'Romania',               code: 'RO', dial: '+40',   flag: '🇷🇴' },
  { name: 'Russia',                code: 'RU', dial: '+7',    flag: '🇷🇺' },
  { name: 'Senegal',               code: 'SN', dial: '+221',  flag: '🇸🇳' },
  { name: 'Sierra Leone',          code: 'SL', dial: '+232',  flag: '🇸🇱' },
  { name: 'Singapore',             code: 'SG', dial: '+65',   flag: '🇸🇬' },
  { name: 'Somalia',               code: 'SO', dial: '+252',  flag: '🇸🇴' },
  { name: 'Spain',                 code: 'ES', dial: '+34',   flag: '🇪🇸' },
  { name: 'Sri Lanka',             code: 'LK', dial: '+94',   flag: '🇱🇰' },
  { name: 'Sudan',                 code: 'SD', dial: '+249',  flag: '🇸🇩' },
  { name: 'Sweden',                code: 'SE', dial: '+46',   flag: '🇸🇪' },
  { name: 'Switzerland',           code: 'CH', dial: '+41',   flag: '🇨🇭' },
  { name: 'Syria',                 code: 'SY', dial: '+963',  flag: '🇸🇾' },
  { name: 'Tajikistan',            code: 'TJ', dial: '+992',  flag: '🇹🇯' },
  { name: 'Tanzania',              code: 'TZ', dial: '+255',  flag: '🇹🇿' },
  { name: 'Thailand',              code: 'TH', dial: '+66',   flag: '🇹🇭' },
  { name: 'Tunisia',               code: 'TN', dial: '+216',  flag: '🇹🇳' },
  { name: 'Turkmenistan',          code: 'TM', dial: '+993',  flag: '🇹🇲' },
  { name: 'Uganda',                code: 'UG', dial: '+256',  flag: '🇺🇬' },
  { name: 'Ukraine',               code: 'UA', dial: '+380',  flag: '🇺🇦' },
  { name: 'Uzbekistan',            code: 'UZ', dial: '+998',  flag: '🇺🇿' },
  { name: 'Yemen',                 code: 'YE', dial: '+967',  flag: '🇾🇪' },
  { name: 'Zimbabwe',              code: 'ZW', dial: '+263',  flag: '🇿🇼' },
]
